# Generated by Django 6.0.6 on 2026-06-20 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequesterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_display_name', models.BooleanField(default=True)),
                ('can_view_email', models.BooleanField(default=False)),
                ('can_view_phone', models.BooleanField(default=False)),
                ('can_view_job_title', models.BooleanField(default=False)),
                ('can_view_linkedin', models.BooleanField(default=False)),
                ('can_view_social_media', models.BooleanField(default=False)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identities.context')),
                ('requester_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identities.requestertype')),
            ],
        ),
        migrations.CreateModel(
            name='ContextProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('linkedin', models.URLField(blank=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('social_media', models.TextField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_profiles', to=settings.AUTH_USER_MODEL)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='identities.context')),
            ],
            options={
                'unique_together': {('account', 'context')},
            },
        ),
    ]
