# Generated by Django 6.0.6 on 2026-06-20 21:19
from django.db import migrations


def create_initial_data(apps, schema_editor):
    Context = apps.get_model('identities', 'Context')
    RequesterType = apps.get_model('identities', 'RequesterType')

    # Defining the requerter types
    requester_types = [
        {
            "name": "Public",
            "description": "Anonymous or general public users"
        },
        {
            "name": "Recruiter",
            "description": "Looking up users for recruitment purposes"
        },
        {
            "name": "Friend",
            "description": "Friends contacts"
        },
        {
            "name": "Family",
            "description": "Family contacts"
        },
        {
            "name": "Colleague",
            "description": "Professional coworkers and teammates"
        },
        {
            "name": "Unknown",
            "description": "No known relationship"
        }
    ]

    for rt in requester_types:
        RequesterType.objects.get_or_create(
            name=rt["name"],
            defaults={
                "description": rt["description"]
            }
        )

    # defining the contexts
    contexts = [
        {
            "name": "Professional",
            "description": "Professional and career related profile"
        },
        {
            "name": "Public",
            "description": "Public facing profile information"
        },
        {
            "name": "Social",
            "description": "Personal and social interactions"
        },
        {
            "name": "Online",
            "description": "Online communities and digital presence"
        }
    ]

    for ctx in contexts:
        Context.objects.get_or_create(
            name=ctx["name"],
            defaults={
                "description": ctx["description"]
            }
        )

# In case of roll back
def reverse_initial_data(apps, schema_editor):
    Context = apps.get_model('identities', 'Context')
    RequesterType = apps.get_model('identities', 'RequesterType')

    Context.objects.filter(
        name__in=[
            "Professional",
            "Public",
            "Social",
            "Online"
        ]
    ).delete()

    RequesterType.objects.filter(
        name__in=[
            "Public",
            "Recruiter",
            "Friend",
            "Family",
            "Colleague",
            "Unknown"
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_initial_data,
            reverse_initial_data
        ),
    ]