# Generated by Django 6.0.6 on 2026-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('context', 'requester_type'), name='unique_context_requester_type'),
        ),
    ]
