# Generated by Django 6.0.6 on 2026-06-21 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_alter_context_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='policy',
            name='unique_context_requester_type',
        ),
        migrations.AddField(
            model_name='policy',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('account', 'context', 'requester_type'), name='unique_user_context_requester'),
        ),
    ]
