# Generated by Django 6.0.6 on 2026-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_remove_policy_unique_context_requester_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='can_view_nickname',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='can_view_organization',
            field=models.BooleanField(default=False),
        ),
    ]
