# Generated by Django 6.0.6 on 2026-08-15 18:51

from django.db import migrations

def add_more_contexts(apps, schema_editor):
    Context = apps.get_model('identities', 'Context')
    contexts = [
        {
            "name": "Governmental/Legal",
            "description": "Government, legal, and official identity information"
        },
        {
            "name": "Academic",
            "description": "Education and academic-related profile information"
        },
        {
            "name": "Personal",
            "description": "Private and personal identity information"
        }
    ]

    for ctx in contexts:
        Context.objects.get_or_create(
            name=ctx["name"],
            defaults={
                "description": ctx["description"]
            }
        )


def reverse_more_contexts(apps, schema_editor):
    Context = apps.get_model('identities', 'Context')
    Context.objects.filter(
        name__in=[
            "Governmental/Legal",
            "Academic",
            "Personal"
        ]
    ).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('identities', '0006_identityrequest'),
    ]

    operations = [
        migrations.RunPython(
            add_more_contexts,
            reverse_more_contexts
        ),
    ]
