# Generated by Django 6.0.6 on 2026-08-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0007_add_more_contexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='preferred_contact_way',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
