# Generated by Django 6.0.6 on 2026-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0008_contextprofile_bio_contextprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='can_view_bio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='can_view_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='can_view_preferred_contact_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='can_view_pronouns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='can_view_university',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='can_view_website',
            field=models.BooleanField(default=False),
        ),
    ]
