# Generated by Django 6.0.6 on 2026-08-15 20:37

from django.db import migrations

def add_more_requester_types(apps, schema_editor):
    RequesterType = apps.get_model('identities', 'RequesterType')

    requester_types = [
        {
            "name": "Classmate",
            "description": "Fellow students or classmates"
        },
        {
            "name": "Professor",
            "description": "Professors, lecturers or academic staff"
        },
        {
            "name": "Client",
            "description": "Existing or prospective clients"
        },
        {
            "name": "Business Partner",
            "description": "Business partners and professional collaborators"
        },
        {
            "name": "Service Provider",
            "description": "Individuals or organizations providing services"
        },
        {
            "name": "Government Official",
            "description": "Government representatives acting in an official capacity"
        },
        {
            "name": "Legal Representative",
            "description": "Lawyers or authorized legal representatives"
        },
        {
            "name": "Other",
            "description": "A requester that does not fit another category"
        }
    ]

    for rt in requester_types:
        RequesterType.objects.get_or_create(
            name=rt["name"],
            defaults={
                "description": rt["description"]
            }
        )

def reverse_more_requester_types(apps, schema_editor):
    RequesterType = apps.get_model('identities', 'RequesterType')

    RequesterType.objects.filter(
        name__in=[
            "Classmate",
            "Professor",
            "Client",
            "Business Partner",
            "Service Provider",
            "Government Official",
            "Legal Representative",
            "Other"
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0009_policy_can_view_bio_policy_can_view_location_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_more_requester_types,
            reverse_more_requester_types
        ),
]
